### ISSUE TITLE
log/err_log path

### ISSUE THREAD

**Issue by ktimothy** [mojombo/god#166]
I have noticed, that god tries to take the log/err_log file relatively to the path where god process was started.
Such behavior is annoying when using capistrano and multiple applications, monitored by god.

**Comment by SymphonicJohn** [comment]
@ktimothy - this is going back quite a while, but did you find a workaround for this?
My deploys are failing with:
`rake aborted!
NameError: uninitialized constant God::Logger::SysLogger`
but only for my production server, and not staging.

**Comment by ktimothy** [comment]
@SymphonicJohn yeah. I migrated to https://github.com/kostya/eye =)
