### ISSUE TITLE
Deprecated `rb_thread_select` removed from trunk.

### ISSUE THREAD

**Issue by phyllisstein** [mojombo/god#194]
Hi there! I wanted to report that I'm having some trouble with God (hah) and the Ruby 2.2 previews. Trying to invoke the executable, I get messages like this:

```
ruby /usr/local/rvm/gems/ruby-head@global/bin/god -c /etc/sidekiq_manager.god -D: symbol lookup error: /usr/local/rvm/gems/ruby-head@global/gems/god-0.13.4/ext/god/netlink_handler_ext.so: undefined symbol: rb_thread_select
```

I think `rb_thread_select` was deprecated, and has finally been taken out of trunk, based on reports from EventMachine users and developers (e.g., eventmachine/eventmachine#495). Thought it might be something worth looking into before the next official release.

Thanks so much for your work on this totally invaluable gem, and take care!

**Comment by eiked** [comment]
I'd like to confirm the problem with god 0.13.1
but it is gone with god 0.13.6
ruby 2.2.2p88 (2015-03-25 revision 50085) [x86_64-linux]
Linux *** 2.6.18-028stab101.1 #1 SMP Sun Jun 24 19:50:48 MSD 2012 x86_64 x86_64 x86_64 GNU/Linux
