### ISSUE TITLE
[GOD]: Next release date?

### ISSUE THREAD

**Issue by chiriaev** [mojombo/god#213]
Guys, Hi. Wondering if you have any dates for the next package iteration. I am interested in the inclusion of this, "https://github.com/mojombo/god/blob/master/lib/god/contacts/sensu.rb", feature. 

Thanks in advance.

Regards, Andrei

**Comment by eric** [comment]
I've just released 0.13.6:

```
Successfully registered gem: god (0.13.6)
```

**Comment by chiriaev** [comment]
Thanks, Eric! Regards, Andrei
