### ISSUE TITLE
god and log rotation (logrotate)

### ISSUE THREAD

**Issue by ktimothy** [mojombo/god#218]
This is a part of my conf file:
```
God.watch do |w|
  w.name = "myproc_1"
  w.group = "myproc"
  
  w.start = "node App.js"
    
  w.log =     File.join(config_path, "..", "..", "logs", "node.log")
  w.err_log = File.join(config_path, "..", "..", "logs", "node.log")
  ...
end
```

I started using unix's logrotate for ```node.log```. The file was renamed to ```node.log.1```, but god continued writing log data to rotated file, instead of creating new node.log.

What can I do to force god to create new log file every time it is rotated?

**Comment by carsonreinke** [comment]
This is usually done using a SIGHUP, but you probably want to look at just changing your logrotate configuration to use `copytruncate`.

**Comment by ktimothy** [comment]
Thanks a lot, that solves the issue.
