### ISSUE TITLE
God cannot run activities as root user (sudo)?

### ISSUE THREAD

**Issue by plukevdh** [mojombo/god#22]
I have a process that I need to run as root using sudo ( a node.js instance ) and the proces hangs in the "starting" state when trying to run first time. I think this is probably because I'm not being given the option to enter the password when sudo tries to run. 

Is there a good way around this or is this an enhancement to pursue?

**Comment by commanderk33n** [comment]
This is just awesome lol: "God cannot run activities as root user (sudo)?"  Yeah, that's why:
![akhgeto](https://user-images.githubusercontent.com/6609667/26949114-00238ca4-4c99-11e7-8aad-ab04f8bc7ce1.jpg)

**Comment by btguys** [comment]
我 06/08/2017 (四)不在k公室，直到 06/14/2017 (三)才返回。

本人休假至14（周三），急事j66595528.


注意: 这是对您消息的自动响应  "Re: [mojombo/god] God cannot run activities
as root user (sudo)? (#22)" 发送日期 6/9/2017 4:23:06 AM.

此通知是此用户离开期间您将收到的唯一通知。
