### ISSUE TITLE
How god runs a non-root user command

### ISSUE THREAD

**Issue by jmscholen** [mojombo/god#220]
I have god running as root user and I have my application running as rails user. I have had trouble setting up the start command to run as my rails user so I ended up getting this to work:
`w.start = "su - rails -c './app/lib/daemons/daemon_runner start' "`

My root user runs under a different version of ruby, so in my various attempts to get the command to run under god resulted in not being able to load env variables. 

Is there a better way to have god run my non-root commands? I tried `w.uid = 'rails'` but that did not work in my situation.

Here's my god config file: https://gist.github.com/jmscholen/065c762abfae9fc44444

**Comment by oscarsan** [comment]
Could this be caused by the fact you are using RVM, have you tried using the [rvm god wrapper](https://rvm.io/deployment/god) when starting god. It works fine with me when just changing the w.uid to the correct user.

**Comment by jmscholen** [comment]
I am using rvm. I'll look into it. thanks.
