### ISSUE TITLE
God misreports permissions when run as a non-root user

### ISSUE THREAD

**Issue by ajsharp** [mojombo/god#43]
When i try to run god as the "deploy" user on one of our servers, I see the following output int the god log:

```
E [2011-05-23 18:23:43] ERROR: PID file directory '/var/www/api/shared/pids' is not writable by deploy                                                                                                        
E [2011-05-23 18:23:43] ERROR: Log file '/dev/null' exists but is not writable by deploy                                                                                                                      
E [2011-05-23 18:23:43] ERROR: Task 'api-unicorn-master-1' is not valid (see above) 
```

However, an `ls -la` on the shared/pids directory shows that the deploy user does have write permissions:

```
# ls -la /var/www/api/shared/pids
drwxrwxr-x 2 deploy deploy 4096 May 23 18:21 .                                                                                                                                                                
drwxrwxr-x 8 deploy deploy 4096 May 20 21:55 ..
```

The second line in the god log output -- related to /dev/null not being accessible -- may be another bug, but not related to permissions. I have log file locations specified both for the process god is managing, yet god is still trying to use /dev/null for logging, apparently.

**Comment by thiagofigueiro** [comment]
Happy birthday, misleading error message.  At least we're able to find this thread that explains w.uid and w.gid are not permitted when God is not running as root.

**Comment by jakotremblay** [comment]
+1
